### ISSUE TITLE
when code release?

### ISSUE THREAD

**Issue by aosokin** [Meituan-AutoML/CPVT#1]
Hi, I've just found your paper https://arxiv.org/abs/2102.10882 on arXiv, the method looks very interesting, but I have not found the released code. Do you plan to release code in this repo? When do you plan to release code?
Best,
Anton

**Comment by cxxgtxy** [comment]
Thanks for your attention to our work.
We plan to  release the code in March.
Besides, the PEG code is already provided in the paper.

**Comment by Danee-wawawa** [comment]
Thank you for your work. When do you plan to release code?

**Comment by cxxgtxy** [comment]
> Thank you for your work. When do you plan to release code?
It's coming soon, and we will release it with another paper together.
Thanks!

**Comment by cxxgtxy** [comment]
> Thank you for your work. When do you plan to release code?

It's coming soon, and we will release it with another paper together.
Thanks!

**Comment by xiaohu2015** [comment]
@Danee-wawawa @aosokin maybe you look at this https://github.com/xiaohu2015/pvt_detectron2

**Comment by cxxgtxy** [comment]
Hi, guys. 
Thanks for your patience. 
We have released the code of CPVT in https://github.com/Meituan-AutoML/Twins.git, where PCPVT is designed based on CPVT and PVT. PCPVT is easy to be implemented and on par with Swin transformer.
We recommend you to use that since it's quite friendly to use across many down stream tasks such as object detection and segmentation.  
Welcome any suggestions.
